export const styles = {
    container: {
      display: 'flex',
      height: '100vh',
      backgroundColor: '#f0f2f5', // Light background for a clean look
    },
    mainContent: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      padding: '30px',
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    actionButtons: {
      display: 'flex',
      gap: '15px',
      marginBottom: '25px',
    },
    actionButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      color: '#fff',
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
      backgroundColor: '#007bff',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
    },
    contentArea: {
      flex: 1,
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '30px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    form: {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '25px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    formGroup: {
      marginBottom: '20px',
      color: '#333333',
    },
    input: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    select: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    submitButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#28a745',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    deleteButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#dc3545',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    tableContainer: {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '25px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse',
      marginTop: '20px',
    },
    tableHeader: {
      backgroundColor: '#f8f9fa',
      fontWeight: 'bold',
      textAlign: 'left',
      padding: '12px',
      border: '1px solid #dee2e6',
      fontSize: '16px',
    },
    tableCell: {
      padding: '12px',
      border: '1px solid #dee2e6',
      fontSize: '16px',
      color: '#333333',
    },
    
  };