export const styles = {
    container: {
      display: 'flex',
      height: '100vh',
      backgroundColor: '#f0f2f5', // Light background for a clean look
    },
    mainContent: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      padding: '30px',
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    actionButtons: {
      display: 'flex',
      gap: '15px',
      marginBottom: '25px',
    },
    actionButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      color: '#fff',
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
      backgroundColor: '#007bff',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
    },
    contentArea: {
      flex: 1,
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '30px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    form: {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '25px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    formGroup: {
      marginBottom: '20px',
      color: '#333333',
    },
    input: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    select: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    submitButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#28a745',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    deleteButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#dc3545',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    tableContainer: {
      margin: "20px",
      overflowX: "auto",
      padding: "20px",
      backgroundColor: "#f9f9f9",
      borderRadius: "8px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      fontFamily: "'Arial', sans-serif",
      borderRadius: "8px",
      overflow: "hidden",
    },
    tableHeader: {
      backgroundColor: "#007bff",
      color: "white",
      padding: "12px 15px",
      textAlign: "left",
      fontSize: "16px",
    },
    tableCell: {
      padding: "12px 15px",
      textAlign: "left",
      borderBottom: "1px solid #ddd",
      wordBreak: "break-word", // Ensures long text wraps
      maxWidth: "300px", // Controls max width of the cell to prevent overflow
    },
    tableRow: {
      cursor: "pointer",
      transition: "background-color 0.3s",
    },
    tableRowHover: {
      backgroundColor: "#f1f1f1", // Adds hover effect
    },
    form: {
      width: '80%',
      margin: '0 auto',
    },
    formGroup: {
      marginBottom: '15px',
    },
    input: {
      width: '100%',
      padding: '8px',
      margin: '5px 0',
      border: '1px solid #ccc',
      borderRadius: '4px',
    },
    selectInput: {
      width: '100%',
      padding: '8px',
      margin: '5px 0',
      border: '1px solid #ccc',
      borderRadius: '4px',
      minHeight: '40px',
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    tag: {
      backgroundColor: '#e0e0e0',
      margin: '3px',
      padding: '5px 10px',
      borderRadius: '15px',
      display: 'flex',
      alignItems: 'center',
    },
    removeTagButton: {
      marginLeft: '5px',
      background: 'transparent',
      border: 'none',
      cursor: 'pointer',
    },
    dropdown: {
      position: 'absolute',
      backgroundColor: 'white',
      boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.1)',
      borderRadius: '4px',
      zIndex: 10,
      width: '100%',
      maxHeight: '200px',
      overflowY: 'auto',
      marginTop: '5px',
      border: '1px solid #ccc',
    },
    dropdownSearch: {
      width: '100%',
      padding: '8px',
      border: '1px solid #ccc',
      borderRadius: '4px',
      marginBottom: '5px',
    },
    dropdownItem: {
      padding: '10px',
      cursor: 'pointer',
      '&:hover': {
        backgroundColor: '#f1f1f1',
      },
    },
    submitButton: {
      padding: '10px 20px',
      backgroundColor: '#4caf50',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
    },
    
  };