export const styles = {
    container: {
      display: 'flex',
      height: '100vh',
      backgroundColor: '#f0f2f5', // Light background for a clean look
    },
    mainContent: {
      flex: 1,
      display: 'flex',
      flexDirection: 'column',
      padding: '30px',
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    actionButtons: {
      display: 'flex',
      gap: '15px',
      marginBottom: '25px',
    },
    actionButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      color: '#fff',
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
      backgroundColor: '#007bff',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
    },
    contentArea: {
      flex: 1,
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '30px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
    },
    form: {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      padding: '25px',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
      color: '#333333',
      width: '50%'
    },
    formGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: '8px',
    },
    input: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    select: {
      width: '100%',
      padding: '10px 15px',
      borderRadius: '8px',
      border: '1px solid #ddd',
      fontSize: '16px',
      color: '#333333',
      boxShadow: 'inset 0 2px 4px rgba(0, 0, 0, 0.05)',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    },
    submitButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#28a745',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    deleteButton: {
      padding: '12px 24px',
      border: 'none',
      borderRadius: '8px',
      backgroundColor: '#dc3545',
      color: '#fff',
      fontWeight: 'bold',
      fontSize: '16px',
      cursor: 'pointer',
      boxShadow: '0 2px 6px rgba(0, 0, 0, 0.1)',
      transition: 'background-color 0.3s ease, transform 0.2s ease',
    },
    tableContainer: {
      margin: "20px",
      overflowX: "auto",
      padding: "20px",
      backgroundColor: "#f9f9f9",
      borderRadius: "8px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      fontFamily: "'Arial', sans-serif",
      borderRadius: "8px",
      overflow: "hidden",
    },
    tableHeader: {
      backgroundColor: "#007bff",
      color: "white",
      padding: "12px 15px",
      textAlign: "left",
      fontSize: "16px",
    },
    tableCell: {
      padding: "12px 15px",
      textAlign: "left",
      borderBottom: "1px solid #ddd",
      wordBreak: "break-word", // Ensures long text wraps
      maxWidth: "300px", // Controls max width of the cell to prevent overflow
    },
    tableRow: {
      cursor: "pointer",
      transition: "background-color 0.3s",
    },
    tableRowHover: {
      backgroundColor: "#f1f1f1", // Adds hover effect
    },
    selectInput: {
      width: '100%',
      padding: '8px',
      margin: '5px 0',
      border: '1px solid #ccc',
      borderRadius: '4px',
      minHeight: '40px',
      display: 'flex',
      flexWrap: 'wrap',
      alignItems: 'center',
    },
    tag: {
      backgroundColor: '#e0e0e0',
      margin: '3px',
      padding: '5px 10px',
      borderRadius: '15px',
      display: 'flex',
      alignItems: 'center',
    },
    removeTagButton: {
      marginLeft: '5px',
      background: 'transparent',
      border: 'none',
      cursor: 'pointer',
    },
    dropdown: {
      position: 'absolute',
      backgroundColor: 'white',
      boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.1)',
      borderRadius: '4px',
      zIndex: 10,
      width: '100%',
      maxHeight: '200px',
      overflowY: 'auto',
      marginTop: '5px',
      border: '1px solid #ccc',
    },
    dropdownSearch: {
      width: '100%',
      padding: '8px',
      border: '1px solid #ccc',
      borderRadius: '4px',
      marginBottom: '5px',
    },
    dropdownItem: {
      padding: '10px',
      cursor: 'pointer',
      '&:hover': {
        backgroundColor: '#f1f1f1',
      },
    },
    submitButton: {
      padding: '10px 20px',
      backgroundColor: '#4caf50',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
    },
    tableContainer: {
      padding: "20px",
      backgroundColor: "#fff",
      borderRadius: "8px",
      boxShadow: "0 2px 5px rgba(0, 0, 0, 0.1)",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      marginTop: "20px",
    },
    tableHeader: {
      padding: "10px 15px",
      textAlign: "left",
      backgroundColor: "#f4f4f4",
      fontWeight: "bold",
      borderBottom: "2px solid #ddd",
    },
    tableCell: {
      padding: "10px 15px",
      borderBottom: "1px solid #ddd",
    },
    inputField: {
      width: "100%",
      padding: "8px",
      border: "1px solid #ccc",
      borderRadius: "4px",
    },
    selectField: {
      width: "100%",
      padding: "8px",
      border: "1px solid #ccc",
      borderRadius: "4px",
      backgroundColor: "#fff",
    },
    selectInput: {
      display: "flex",
      flexWrap: "wrap",
      padding: "8px",
      border: "1px solid #ccc",
      borderRadius: "4px",
      backgroundColor: "#fff",
      cursor: "pointer",
      minHeight: "36px",
    },
    tag: {
      display: "flex",
      alignItems: "center",
      margin: "2px 5px",
      padding: "5px",
      backgroundColor: "#f0f0f0",
      borderRadius: "3px",
    },
    removeTagButton: {
      marginLeft: "5px",
      background: "none",
      border: "none",
      color: "red",
      cursor: "pointer",
      fontWeight: "bold",
    },
    updateButton: {
      padding: "10px 20px",
      backgroundColor: "#28a745",
      color: "#fff",
      border: "none",
      borderRadius: "4px",
      cursor: "pointer",
    },
    container: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: '20px', // Add space between form and permission div
      width: '100%',
    },
    form: {
      flex: 1,
      maxWidth: '60%', // Control the width of the form
      padding: '20px',
      border: '1px solid #ccc',
      borderRadius: '5px',
    },
    permission: {
      flex: 1,
      maxWidth: '40%', // Control the width of the permission div
      padding: '20px',
      textAlign: 'center',
      border: '1px solid #ccc',
      borderRadius: '5px',
      backgroundColor: '#f9f9f9',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    formGroup: {
      marginBottom: '15px',
    },

    selectInput: {
      width: '100%',
      padding: '10px',
      border: '1px solid #ccc',
      borderRadius: '5px',
      display: 'flex',
      flexWrap: 'wrap',
      gap: '5px',
      alignItems: 'center',
      cursor: 'pointer',
    },
    tag: {
      display: 'inline-flex',
      alignItems: 'center',
      backgroundColor: '#007bff',
      color: '#fff',
      borderRadius: '3px',
      padding: '5px 10px',
      marginRight: '5px',
    },
    removeTagButton: {
      marginLeft: '5px',
      backgroundColor: 'transparent',
      border: 'none',
      color: '#fff',
      cursor: 'pointer',
    },
    dropdown: {
      marginTop: '5px',
      border: '1px solid #ccc',
      borderRadius: '5px',
      maxHeight: '150px',
      overflowY: 'auto',
      backgroundColor: '#fff',
    },
    dropdownSearch: {
      width: '100%',
      padding: '10px',
      border: '1px solid #ccc',
      borderRadius: '5px',
      marginBottom: '5px',
    },
    dropdownItem: {
      padding: '10px',
      cursor: 'pointer',
      borderBottom: '1px solid #eee',
    },
    submitButton: {
      width: '100%',
      padding: '10px',
      backgroundColor: '#28a745',
      color: '#fff',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
    },
    errorInput:{
      color: "red",
      fontSize: "14px",
      marginTop: "5px",
      fontWeight: "bold",
      fontStyle: "italic",
    }
    
    
  };